import { StyleSheet } from "../../Utils/Stylesheet";
import Colors from "../../Utils/Colors";

export const detailsAlunoStyles = StyleSheet.create({
  overlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.8)",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    overflowY: "auto",
    padding: "2vw",
    zIndex: 1000,
  },
  mainContainer: {
    width: "90vw",
    maxWidth: 1200,
    minHeight: "85vh",
    backgroundColor: Colors.surface,
    borderRadius: 20,
    border: `1px solid ${Colors.border}`,
    boxShadow: "0 20px 60px rgba(0, 0, 0, 0.3)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    overflow: "auto",
  },
  header: {
    padding: "1.5rem 2rem",
    borderBottom: `1px solid ${Colors.border}`,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    flexWrap: "wrap",
    gap: "1rem",
  },
  titleSection: {
    flex: "1",
    minWidth: 0,
  },
  title: {
    color: Colors.primary,
    margin: 0,
    fontSize: "clamp(1.25rem, 4vw, 1.75rem)",
    fontWeight: "700",
    marginBottom: "0.25rem",
    wordBreak: "break-word",
  },
  subtitle: {
    color: Colors.textMuted,
    fontSize: "0.875rem",
    opacity: 0.8,
  },
  actions: {
    display: "flex",
    gap: "0.75rem",
    alignItems: "center",
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  buttonText: {
    // Text will automatically hide when container is too small due to flexbox
  },
  editButton: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    padding: "0.625rem 1.25rem",
    backgroundColor: Colors.primary,
    color: "black",
    border: "none",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "0.875rem",
    transition: "all 0.2s ease",
    whiteSpace: "nowrap",
    minWidth: "min-content",
  },
  saveButton: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    padding: "0.625rem 1.25rem",
    backgroundColor: "#10b981",
    color: "black",
    border: "none",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "0.875rem",
    transition: "all 0.2s ease",
    whiteSpace: "nowrap",
    minWidth: "min-content",
  },
  discardButton: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    padding: "0.625rem 1.25rem",
    backgroundColor: "#f59e0b",
    color: "black",
    border: "none",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "0.875rem",
    transition: "all 0.2s ease",
    whiteSpace: "nowrap",
    minWidth: "min-content",
  },
  deleteButton: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    padding: "0.625rem 1.25rem",
    backgroundColor: Colors.error,
    color: "black",
    border: "none",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "0.875rem",
    transition: "all 0.2s ease",
    whiteSpace: "nowrap",
    minWidth: "min-content",
  },
  closeButton: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "2.75rem",
    height: "2.75rem",
    backgroundColor: "rgba(0, 0, 0, 0.1)",
    border: `1px solid ${Colors.border}`,
    borderRadius: "10px",
    color: Colors.textMuted,
    cursor: "pointer",
    transition: "all 0.2s ease",
    flexShrink: 0,
  },
  pagamentoButton: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "2.75rem",
    height: "2.75rem",
    backgroundColor: "rgba(0, 0, 0, 0.1)",
    border: `1px solid ${Colors.border}`,
    borderRadius: "10px",
    color: Colors.textMuted,
    cursor: "pointer",
    transition: "all 0.2s ease",
    flexShrink: 0,
  },
  content: {
    flex: 1,
    padding: "2rem",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "1.5rem",
  },
  row: {
    display: "flex",
    gap: "1.5rem",
    alignItems: "stretch",
    flexWrap: "wrap",
  },
  card: {
    flex: "1 1 300px",
    backgroundColor: Colors.surfaceAlt,
    padding: "1.5rem",
    borderRadius: "16px",
    border: `1px solid ${Colors.border}`,
    minWidth: "min(100%, 300px)",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.05)",
  },
  imageContainer: {
    flex: "0 1 300px",
    display: "flex",
    flexDirection: "column",
  },
  cardTitle: {
    color: Colors.primary,
    fontSize: "1.125rem",
    fontWeight: "600",
    margin: "0 0 1.25rem 0",
    display: "flex",
    alignItems: "center",
    gap: "0.625rem",
  },
  icon: {
    fontSize: "1.25rem",
  },
  fieldsGrid: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  fieldContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "0.375rem",
  },
  label: {
    fontWeight: "600",
    fontSize: "0.8125rem",
    color: Colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  value: {
    color: Colors.text,
    fontSize: "0.9375rem",
    padding: "0.25rem 0",
    minHeight: "1.5rem",
    wordBreak: "break-word",
  },
  notInformed: {
    color: Colors.textMuted,
    fontStyle: "italic",
  },
  input: {
    padding: "0.625rem 0.75rem",
    border: `2px solid ${Colors.border}`,
    borderRadius: "8px",
    fontSize: "0.9375rem",
    backgroundColor: Colors.surface,
    transition: "all 0.2s ease",
    color: Colors.text,
    width: "100%",
    boxSizing: "border-box",
  },
  image: {
    width: "100%",
    height: "auto",
    objectFit: "cover",
    borderRadius: "12px",
    border: `1px solid ${Colors.border}`,
  },
  previewImage: {
    width: "100%",
    height: "auto",
    objectFit: "cover",
    borderRadius: "8px",
    marginTop: "0.75rem",
    border: `1px solid ${Colors.border}`,
  },
  placeholderImage: {
    width: "100%",
    height: "200px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 0, 0, 0.05)",
    borderRadius: "12px",
    border: `2px dashed ${Colors.border}`,
    color: Colors.textMuted,
    fontSize: "0.875rem",
  },
  fileUpload: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  error: {
    color: Colors.error,
    fontSize: "0.75rem",
    marginTop: "0.25rem",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    fontWeight: "600",
    fontSize: "0.8125rem",
    color: Colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    cursor: "pointer",
  },
  checkbox: {
    width: "1rem",
    height: "1rem",
    cursor: "pointer",
  },
});